server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  add_header X-Content-Type-Options nosniff;
  add_header Referrer-Policy same-origin;
  resolver 127.0.0.11 valid=10s ipv6=off;
  location /api/ {
    set $backend api:8088;
    proxy_pass http://$backend$request_uri;
    proxy_read_timeout 60s;
    proxy_set_header Host $host;
  }
  location / { try_files $uri $uri/ /index.html; }
}
